name: network_spreading_models
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pyyaml
  - ipython
  - ipykernel
  - pip
  - pip:
      - bottleneck

